# Generated by Django 4.2 on 2023-05-06 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image_src', models.CharField(max_length=200)),
                ('reference_genome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chromosome', models.IntegerField()),
                ('coordinate', models.IntegerField()),
                ('reference_allele', models.CharField(max_length=1)),
                ('alternative_allele', models.CharField(max_length=1)),
                ('MAF', models.IntegerField()),
                ('species_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snp_app.species')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sampling_date', models.DateTimeField()),
                ('sequencing_date', models.DateTimeField()),
                ('specimen', models.CharField(max_length=100)),
                ('tissue', models.CharField(max_length=100)),
                ('SNP_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snp_app.snip')),
                ('species_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snp_app.species')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('SNP_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snp_app.snip')),
            ],
        ),
        migrations.AddConstraint(
            model_name='snip',
            constraint=models.CheckConstraint(check=models.Q(('alternative_allele', models.F('reference_allele')), _negated=True), name='snips_cannot_be_equal'),
        ),
        migrations.AlterUniqueTogether(
            name='snip',
            unique_together={('chromosome', 'coordinate')},
        ),
    ]
