# Generated by Django 4.2 on 2023-05-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snp_app', '0002_alter_snip_maf_snip_maf_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='SNP_id',
            new_name='SNP',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='SNP_id',
            new_name='SNP',
        ),
        migrations.RenameField(
            model_name='snip',
            old_name='species_name',
            new_name='species',
        ),
    ]
