# Generated by Django 4.2 on 2023-05-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snp_app', '0003_rename_snp_id_annotation_snp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='species_name',
            new_name='species',
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together={('name', 'SNP')},
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(check=models.Q(('sequencing_date__gte', models.F('sampling_date'))), name='sequencing_later_than_sampling'),
        ),
    ]
