# Generated by Django 4.2 on 2023-05-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snp_app', '0004_rename_species_name_sample_species_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together={('sampling_date', 'specimen', 'species', 'tissue')},
        ),
        migrations.RemoveField(
            model_name='sample',
            name='SNP',
        ),
    ]
