# Generated by Django 4.2 on 2023-05-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snp_app', '0005_alter_sample_unique_together_remove_sample_snp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sampling_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sequencing_date',
            field=models.DateField(),
        ),
    ]
