# Generated by Django 4.2 on 2023-05-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snp_app', '0007_remove_species_image_src_species_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='species',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SNP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.IntegerField()),
                ('coordinate', models.IntegerField()),
                ('reference_allele', models.CharField(max_length=1)),
                ('alternative_allele', models.CharField(max_length=1)),
                ('MAF', models.FloatField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snp_app.species')),
            ],
        ),
        migrations.AlterField(
            model_name='annotation',
            name='SNP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snp_app.snp'),
        ),
        migrations.DeleteModel(
            name='Snip',
        ),
        migrations.AddConstraint(
            model_name='snp',
            constraint=models.CheckConstraint(check=models.Q(('alternative_allele', models.F('reference_allele')), _negated=True), name='snips_cannot_be_equal'),
        ),
        migrations.AddConstraint(
            model_name='snp',
            constraint=models.CheckConstraint(check=models.Q(('MAF__gte', 0.0), ('MAF__lte', 1.0)), name='MAF_range'),
        ),
        migrations.AlterUniqueTogether(
            name='snp',
            unique_together={('chromosome', 'coordinate')},
        ),
    ]
