# Generated by Django 4.2 on 2023-06-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snp_app', '0009_remove_snp_species_snp_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
