# Generated by Django 4.2 on 2023-06-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snp_app', '0010_alter_animal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='date',
        ),
        migrations.AddField(
            model_name='annotation',
            name='type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='text',
            field=models.CharField(max_length=5000),
        ),
    ]
